version: "3"

services:
  consul:
    container_name: consul
    image: consul:latest
    ports:
      - "8500:8500"
      - "8300:8300"
    volumes:
      - ./config:/config
      - ./_data/consul:/data
    command: agent -server -data-dir=/data -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1 --ui
  logger:
    build: ./Services/DistributedLogger/
    depends_on:
      - consul
    restart: on-failure
  message_queue_consumer:
    build: Services/MessageQueueConsumer/
    command: ["./MessageQueueManager","-amqp","amqp://guest:guest@rmq_server:5672/", "-host", "message_queue_consumer", "-port","3001"]
    ports:
      - 3001
    depends_on:
      - rmq_server
    restart: on-failure
  producer:
    build: ./Producer/
    depends_on:
      - logger
  rmq_server:
#    image: rabbitmq
    build: Services/RabbitMQDocker
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq-server"
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD"
        - "rabbitmqctl"
        - "status"

#  vault:
#    container_name: vault
#    image: vault
#    links:
#      - consul:consul
#    depends_on:
#      - consul
#    ports:
#      - "8200:8200"
#    volumes:
#      - ./config:/config
#      - ./_data/consul:/data
#    cap_add:
#      - IPC_LOCK
#    command: server -config=/config/vault.hcl
#
#  webui:
#    container_name: webui
#    image: djenriquez/vault-ui
#    ports:
#      - "8000:8000"
#    links:
#      - vault:vault
#    environment:
#      NODE_TLS_REJECT_UNAUTHORIZED: 0
#      VAULT_URL_DEFAULT: https://vault:8200

#  backup:
#    container_name: backup
#    build: backup/
#    links:
#      - consul:consul
#    volumes:
#      - ./_data/backup:/backup/
#    command: consul-backup